services:
  db:
    container_name: db
    image: mariadb:11.3.2-jammy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: charity-db
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "3000:80"
      - "3001:443"
    volumes:
      - ./FE/stacks:/appsmith-stacks
    restart: unless-stopped
  pmnm:
    container_name: pmnm
    image: quythanh/pmnm:latest
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./BE:/app
    env_file:
      - ./BE/.env
