# Generated by Django 5.1.3 on 2024-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
