# Generated by Django 5.1.3 on 2024-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('victim_name', models.CharField(max_length=50)),
                ('victim_problem', models.CharField(max_length=100)),
                ('victim_solution', models.TextField()),
                ('victim_place', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='chat',
            name='firebase_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
