# Generated by Django 5.1.3 on 2024-12-04 12:15

import CharityApp.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('way', django_enumfield.db.fields.EnumField(default=0, enum=CharityApp.models.WayType)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_applies', to='CharityApp.donationcampaign')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_applies', to='CharityApp.supplytype')),
                ('wareHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_applies', to='CharityApp.storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
