# Generated by Django 5.1.3 on 2024-12-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0002_alter_approval_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplytype',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
    ]
