# Generated by Django 5.1.3 on 2024-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0002_helprequest_alter_chat_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='victim_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='victim_place',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='victim_problem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
