# Generated by Django 5.1.3 on 2024-12-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0002_stockapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPostHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('donated', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated', to='CharityApp.donationpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_donated', to='CharityApp.civilian')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
