# Generated by Django 5.1.3 on 2024-12-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0003_donationposthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockapply',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CharityApp.location'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='logo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detaildonationreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='CharityApp.donationreport'),
        ),
        migrations.AlterField(
            model_name='location',
            name='current_status',
            field=models.CharField(default='Bình thường', max_length=100),
        ),
    ]
