# Generated by Django 5.1.3 on 2024-12-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0003_supplytype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='supply_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='CharityApp.supplytype'),
        ),
    ]
