# Generated by Django 5.1.3 on 2024-12-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0003_donationposthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.CharField(default='https://assets.appsmith.com/widgets/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='real_path',
            field=models.CharField(max_length=255),
        ),
    ]
