# Generated by Django 5.1.3 on 2024-12-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0004_article_content_article_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
