# Generated by Django 5.1.3 on 2024-11-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='time_id',
            field=models.IntegerField(default=1),
        ),
    ]
