# Generated by Django 5.1.3 on 2024-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0002_approval_time_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
