# Generated by Django 5.1.3 on 2024-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0003_approval_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(default='ABC', max_length=50),
        ),
    ]
