# Generated by Django 5.1.3 on 2024-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0004_donationcampaign_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='is_approved',
            field=models.BooleanField(),
        ),
    ]
